import 
{SET_AUTH_LOADING,
REMOVE_AUTH_LOADING,
LOGIN_SUCCESS,
LOGIN_FAIL,
USER_LOADED_SUCCESS,
USER_LOADED_FAIL,
AUTHENTICATED_SUCCESS,
AUTHENTICATED_FAIL,
REFRESH_SUCCESS,
REFRESH_FAIL,
LOGOUT}
from "./Types"
import axios from "axios"

